x-runtipi:
  schema_version: 2

services:
  weaver:
    image: ghcr.io/scryer-media/weaver:0.13.3
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      WEAVER_BOOTSTRAP_LOGIN_USERNAME: ${WEAVER_ADMIN_USERNAME}
      WEAVER_BOOTSTRAP_LOGIN_PASSWORD: ${WEAVER_ADMIN_PASSWORD}
      WEAVER_HTTP_ALLOWED_HOSTS: weaver,${APP_HOST}
      WEAVER_INTERMEDIATE_DIR: /data/downloads/usenet/intermediate
      WEAVER_COMPLETE_DIR: /data/downloads/usenet/complete
      WEAVER_STRICT_SECURITY: "1"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - type: bind
        source: ${RUNTIPI_MEDIA_DIR}
        target: /data
        bind:
          propagation: rslave
    x-runtipi:
      is_main: true
      internal_port: 9090
