x-runtipi:
  schema_version: 2

services:
  scryer:
    image: ghcr.io/scryer-media/scryer:0.21.10
    environment:
      PUID: ${UID:-0}
      PGID: ${GID:-0}
      TZ: ${TZ}
      SCRYER_PUBLIC_URL: ${APP_PROTOCOL}://${APP_DOMAIN}
      SCRYER_METADATA_GATEWAY_GRAPHQL_URL: https://smg.scryer.media/graphql
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - type: bind
        source: ${ROOT_FOLDER_HOST}/media
        target: /data
        bind:
          propagation: rslave
    x-runtipi:
      is_main: true
      internal_port: 8080
