import fs from "node:fs";
import path from "node:path";

const appsRoot = path.join(process.cwd(), "apps");
const readmePath = path.join(process.cwd(), "README.md");

const START = "<!-- APPS:START - generated by .github/scripts/readme-generator.ts, do not edit by hand -->";
const END = "<!-- APPS:END -->";

type Config = {
  id: string;
  name: string;
  short_desc: string;
  source?: string;
  website?: string;
  available?: boolean;
};

const getConfigs = (): Config[] => {
  return fs
    .readdirSync(appsRoot)
    .filter((entry) => fs.statSync(path.join(appsRoot, entry)).isDirectory())
    .map((id) => {
      const configPath = path.join(appsRoot, id, "config.json");
      if (!fs.existsSync(configPath)) {
        return null;
      }
      return JSON.parse(fs.readFileSync(configPath, "utf-8")) as Config;
    })
    .filter((config): config is Config => config !== null && config.available !== false)
    .sort((a, b) => a.id.localeCompare(b.id));
};

const buildTable = (configs: Config[]): string => {
  const rows = configs.map((config) => {
    const link = config.source || config.website;
    const name = link ? `[${config.name}](${link})` : config.name;
    return `| <img src="apps/${config.id}/metadata/logo.jpg" width="32"> | ${name} | ${config.short_desc} |`;
  });

  return ["| | Name | Description |", "|---|---|---|", ...rows].join("\n");
};

const main = (): void => {
  const configs = getConfigs();
  const block = `${START}\n${buildTable(configs)}\n${END}`;

  const readme = fs.readFileSync(readmePath, "utf-8");
  const marker = new RegExp(`${START}[\\s\\S]*?${END}`);

  if (!marker.test(readme)) {
    console.error(`README markers not found. Expected "${START}" ... "${END}".`);
    process.exit(1);
  }

  const updated = readme.replace(marker, block);

  if (updated === readme) {
    console.log(`README already up to date (${configs.length} apps).`);
    return;
  }

  fs.writeFileSync(readmePath, updated);
  console.log(`README regenerated with ${configs.length} apps.`);
};

main();
