x-runtipi:
  schema_version: 2

services:
  decypharr:
    image: cy01/blackhole:v2.5
    environment:
      PUID: ${UID:-0}
      PGID: ${GID:-0}
      UMASK: "002"
      TZ: ${TZ}
    volumes:
      - ${APP_DATA_DIR}/config:/app
      - ${ROOT_FOLDER_HOST}/media:/data
    x-runtipi:
      is_main: true
      internal_port: 8282
